[versions]
java = "17"
kotlin = "2.3.0"

[libraries]
demo-groovy = { module = "org.codehaus.groovy:groovy-json", version = "3.0.25" }
demo-commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.20.0" }
junit-bom = { module = "org.junit:junit-bom", version = "6.0.2" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
proguard = { module = "com.guardsquare:proguard-base", version = "7.8.2" }

[plugins]
android = { id = "com.android.application", version = "9.0.0" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "6.0.7" }
dokka = { id = "org.jetbrains.dokka-javadoc", version = "2.1.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-samReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
gitVersion = { id = "io.github.gmazzo.gitversion", version = "1.5.1" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
publicationsReport = { id = "io.github.gmazzo.publications.report", version = "1.3.3" }
